apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: java
          image: oscarruiz15/reservascanchas:v4
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: mysql-connection-configmap
                  key: db-connection-string
---
kind: Service
apiVersion: v1
metadata:
  name: java-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080